sonar.projectKey=cat-frontend
sonar.projectName=Cat Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,build/**

# Optional (if using test coverage)
sonar.javascript.lcov.reportPaths=coverage/lcov.info